#pragma once

#include <glm/glm.hpp>
#include <cmath>
#include <optional>
#include <vector>
#include "imageLoader.h"
struct Triangle
{
	alignas(16)glm::vec3 v0;
	alignas(16)glm::vec3 v1;
	//not 16
	alignas(16)glm::vec3 v2; // vertices
	alignas(4) int matIndex;
	alignas(16)glm::vec3 n0;
	alignas(16)glm::vec3 n1;
	alignas(16)glm::vec3 n2;
	alignas(8)glm::vec2 uv0;
	alignas(8)glm::vec2 uv1;
	alignas(8)glm::vec2 uv2;
	alignas(4)uint32_t hasNormal = false;
	alignas(4)uint32_t hasTexture = false;
	alignas(4)uint32_t colorMapIndex = -1;


	static void AssignMaterialIndexForMesh(std::vector<Triangle>& mesh, uint32_t index)
	{
		for (auto& t : mesh)
		{
			t.matIndex = index;
		}
	}
	static void AssignColorIndexForMesh(std::vector<Triangle>& mesh, uint32_t index)
	{
		for (auto& t : mesh)
		{
			t.colorMapIndex = index;
		}
	}
	static void ActivateTextureForMesh(std::vector<Triangle>& mesh)
	{
		for (auto& t : mesh)
		{
			t.hasTexture = true;
		}
	}
	static void DeactivateTextureForMesh(std::vector<Triangle>& mesh)
	{
		for (auto& t : mesh)
		{
			t.hasTexture = false;
		}
	}
};

struct Sphere
{
	alignas(16)glm::vec3 center;
	float r;
	//16
	int matIndex;
	int lightIndex = -1; // entry in Scene::lights when this sphere is a sphere light
};

enum class LightType : int
{
	Point = 0,
	Spot = 1,
	Directional = 2,
	Sphere = 3,			  // emissive Scene::spheres entry, sampled by solid-angle cone
	EmissiveTriangle = 4, // generated by LightTable from emissive meshes (not stored in Scene)
};

// Analytic light. Area lights are real emissive geometry (see Scene::addQuadLight /
// addSphereLight), so rays can hit them and MIS applies; point/spot/directional are delta lights.
struct Light
{
	LightType type = LightType::Point;
	glm::vec3 color{ 1.0f };
	float intensity = 1.0f;					 // point/spot: radiant intensity; directional: irradiance
	glm::vec3 position{ 0.0f };
	glm::vec3 direction{ 0.0f, 0.0f, -1.0f }; // direction the light travels (spot/directional)
	float innerCone = 0.0f;					 // spot half-angles in radians
	float outerCone = 0.7853982f;
	float radius = 0.0f;					 // Point: > 0 makes it a sphere light (soft, hittable)
	float angle = 0.0f;						 // Directional: angular diameter in radians (0: delta)
	int sphere = -1;						 // LightType::Sphere: index into Scene::spheres
};

struct Material
{
	alignas(16)glm::vec3 albedo;
	float metallic;
	alignas(16)glm::vec3 emission_color;
	float roughness;
	//16
	float emission_power;
	float eta;			  // index of refraction for transmissive materials
	int emissionMap = -1; // color map index modulating emission (glTF emissiveTexture), -1: none
	float transmission = 0.0f;			 // probability of the smooth dielectric lobe (glTF transmission)
	alignas(16) glm::vec3 sigma_a{ 0.0f }; // volume absorption per unit length (Beer-Lambert)
	int thinWalled = 0;					 // 1: transmission without refraction or volume
	float dispersion = 0.0f;			 // KHR_materials_dispersion: 20 / Abbe number (0: none)
	float alphaCutoff = 0.5f;			 // glTF alphaCutoff (MASK)
	int alphaMode = 0;					 // glTF alphaMode: 0 OPAQUE, 1 MASK, 2 BLEND (base color texture alpha)
};
static_assert(sizeof(Material) == 80, "Material must match std430 layout");

// A placement of a mesh in the world. Meshes are stored once; instances only add a transform.
struct MeshInstance
{
	int mesh;
	glm::mat4 transform{1.0f};
	int materialOverride = -1; // -1: use the triangles' own materials
};

// Homogeneous participating medium filling an axis-aligned box (world space).
struct Fog
{
	bool enabled = false;
	glm::vec3 min{ 0.0f }, max{ 0.0f };
	glm::vec3 sigma_s{ 0.0f }; // scattering coefficient per unit length
	glm::vec3 sigma_a{ 0.0f }; // absorption coefficient per unit length
	float g = 0.0f;			   // Henyey-Greenstein anisotropy (> 0: forward scattering)
	glm::mat4 toLocal{ 1.0f };  // rigid map from render space into the box's frame (min/max are there)
};

struct Scene
{
	std::vector<std::vector<Triangle>> meshes; // object-space geometry
	std::vector<MeshInstance> instances;
	std::vector<Light> lights; // analytic lights; emissive meshes are lights implicitly
	std::vector<Sphere> spheres;
	std::vector<Material> mats;
	std::vector<Image> colorMaps;
	HDRI hdr;
	std::optional<glm::mat4> camera; // camera-to-world of the first camera found by a loader
	float cameraYFov = 0.0f;		 // that camera's vertical field of view in radians (0: unknown)
	Fog fog;

	// Re-roots the whole scene: instances, lights and spheres (e.g. into a camera's view space).
	void transformInstances(const glm::mat4& m)
	{
		for (auto& inst : instances)
			inst.transform = m * inst.transform;
		for (auto& l : lights)
		{
			l.position = glm::vec3(m * glm::vec4(l.position, 1.0f));
			l.direction = glm::normalize(glm::mat3(m) * l.direction);
		}
		float radiusScale = std::cbrt(std::abs(glm::determinant(glm::mat3(m))));
		for (auto& s : spheres)
		{
			s.center = glm::vec3(m * glm::vec4(s.center, 1.0f));
			s.r *= radiusScale;
		}
	}

	int addMesh(std::vector<Triangle> triangles)
	{
		meshes.push_back(std::move(triangles));
		return static_cast<int>(meshes.size()) - 1;
	}

	// Bakes every instance whose mesh no other instance uses into one world-space mesh, so the
	// two-level BVH keeps real instancing only where meshes are reused. Overlapping instance
	// bounds make rays enter many BLASes; a single BLAS over the unique geometry avoids that
	// at no memory cost (the merged meshes were not shared).
	void mergeUniqueInstances()
	{
		std::vector<int> uses(meshes.size(), 0);
		for (const auto& inst : instances)
			if (inst.mesh >= 0 && inst.mesh < static_cast<int>(meshes.size()))
				++uses[inst.mesh];
		size_t unique = 0;
		for (const auto& inst : instances)
			if (inst.mesh >= 0 && inst.mesh < static_cast<int>(meshes.size()) && uses[inst.mesh] == 1)
				++unique;
		if (unique < 2)
			return; // nothing to gain
		std::vector<Triangle> merged;
		std::vector<MeshInstance> kept;
		for (const auto& inst : instances)
		{
			if (inst.mesh < 0 || inst.mesh >= static_cast<int>(meshes.size()) || uses[inst.mesh] != 1)
			{
				kept.push_back(inst);
				continue;
			}
			glm::mat3 nrm = glm::transpose(glm::inverse(glm::mat3(inst.transform)));
			// A mirroring transform reverses the winding, and the shader takes front/back
			// (glass entering/leaving) from the winding: swap two vertices to keep it.
			const bool mirrored = glm::determinant(glm::mat3(inst.transform)) < 0.0f;
			for (Triangle t : meshes[inst.mesh])
			{
				t.v0 = glm::vec3(inst.transform * glm::vec4(t.v0, 1.0f));
				t.v1 = glm::vec3(inst.transform * glm::vec4(t.v1, 1.0f));
				t.v2 = glm::vec3(inst.transform * glm::vec4(t.v2, 1.0f));
				t.n0 = glm::normalize(nrm * t.n0);
				t.n1 = glm::normalize(nrm * t.n1);
				t.n2 = glm::normalize(nrm * t.n2);
				if (mirrored)
				{
					std::swap(t.v1, t.v2);
					std::swap(t.n1, t.n2);
					std::swap(t.uv1, t.uv2);
				}
				if (inst.materialOverride >= 0)
					t.matIndex = inst.materialOverride;
				merged.push_back(t);
			}
			meshes[inst.mesh].clear(); // now baked into `merged`
		}
		meshes.push_back(std::move(merged));
		kept.push_back({ static_cast<int>(meshes.size()) - 1, glm::mat4(1.0f), -1 });
		instances = std::move(kept);
	}

	void addInstance(int mesh, const glm::mat4& transform = glm::mat4(1.0f), int materialOverride = -1)
	{
		instances.push_back({ mesh, transform, materialOverride });
	}

	void addLight(const Light& light)
	{
		// A point light with a radius is a sphere light emitting the same intensity
		// (I = L * pi * r^2 towards any direction).
		if (light.type == LightType::Point && light.radius > 0.0f)
		{
			float r = light.radius;
			addSphereLight(light.position, r, light.color * light.intensity / (3.14159265f * r * r));
			return;
		}
		lights.push_back(light);
	}

	// Emissive parallelogram corner + u + v (two triangles, emits from both sides).
	void addQuadLight(const glm::vec3& corner, const glm::vec3& u, const glm::vec3& v, const glm::vec3& radiance)
	{
		int mat = addEmissiveMaterial(radiance);
		glm::vec3 n = glm::normalize(glm::cross(u, v));
		glm::vec3 p0 = corner, p1 = corner + u, p2 = corner + u + v, p3 = corner + v;
		auto tri = [&](glm::vec3 a, glm::vec3 b, glm::vec3 c)
			{
				Triangle t{};
				t.v0 = a; t.v1 = b; t.v2 = c;
				t.n0 = t.n1 = t.n2 = n;
				t.matIndex = mat;
				t.hasNormal = true;
				return t;
			};
		addInstance(addMesh({ tri(p0, p1, p2), tri(p0, p2, p3) }));
	}

	void addSphereLight(const glm::vec3& center, float radius, const glm::vec3& radiance)
	{
		Sphere s{ center, radius, addEmissiveMaterial(radiance) };
		s.lightIndex = static_cast<int>(lights.size());
		Light l;
		l.type = LightType::Sphere;
		l.sphere = static_cast<int>(spheres.size());
		spheres.push_back(s);
		lights.push_back(l);
	}

private:
	int addEmissiveMaterial(const glm::vec3& radiance)
	{
		Material m{};
		m.emission_color = radiance;
		m.emission_power = 1.0f;
		m.roughness = 1.0f;
		mats.push_back(m);
		return static_cast<int>(mats.size()) - 1;
	}
};
